# Generated by Django 6.0.1 on 2026-03-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_options_alter_enrollment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('paid', 'Оплачено'), ('overdue', 'Просрочено')], default='pending', max_length=20, verbose_name='Статус')),
                ('method', models.CharField(blank=True, choices=[('sbp', 'СБП'), ('card', 'Карта'), ('cash', 'Наличные'), ('transfer', 'Перевод')], default='', max_length=20, verbose_name='Способ оплаты')),
                ('period_label', models.CharField(blank=True, default='', max_length=200, verbose_name='За что оплата / период')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
