# Generated by Django 6.0.1 on 2026-03-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курс'},
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('group', 'Групповой'), ('individual', 'Индивидуальный')], default='group', max_length=20, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='course',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Группа / ученик'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Класс / уровень'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Предмет'),
        ),
    ]
