# Generated by Django 6.0.1 on 2026-03-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='homework_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.homework', verbose_name='Домашнее задание')),
            ],
            options={
                'verbose_name': 'Вложение к домашнему заданию',
                'verbose_name_plural': 'Вложения к домашнему заданию',
                'ordering': ['created_at'],
            },
        ),
    ]
