# Generated by Django 6.0.1 on 2026-03-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homeworkattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkattachment',
            options={'ordering': ['created_at'], 'verbose_name': 'Файл преподавателя', 'verbose_name_plural': 'Файлы преподавателя'},
        ),
        migrations.AlterField(
            model_name='homeworkattachment',
            name='file',
            field=models.FileField(upload_to='homework_attachments/%Y/%m/%d/', verbose_name='Файл преподавателя'),
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='homework_submissions/%Y/%m/%d/', verbose_name='Файл ученика')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_attachments', to='homework.homeworkstatus', verbose_name='Статус домашнего задания')),
            ],
            options={
                'verbose_name': 'Файл ответа ученика',
                'verbose_name_plural': 'Файлы ответов учеников',
                'ordering': ['created_at'],
            },
        ),
    ]
