# Generated by Django 6.0.1 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('lesson_reminder', 'Напоминание о занятии'), ('homework_new', 'Новое домашнее задание'), ('homework_deadline', 'Дедлайн ДЗ'), ('homework_overdue', 'Просроченное ДЗ'), ('payment_reminder', 'Напоминание об оплате'), ('quiz_assigned', 'Назначен тест'), ('custom', 'Сообщение от преподавателя')], max_length=30, verbose_name='Тип уведомления')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Журнал уведомлений',
                'verbose_name_plural': 'Журнал уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram chat_id')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Telegram username')),
                ('link_code', models.CharField(blank=True, help_text='Код, который ученик отправляет боту для привязки', max_length=64, verbose_name='Код привязки')),
                ('is_linked', models.BooleanField(default=False, verbose_name='Привязан')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-профиль',
                'verbose_name_plural': 'Telegram-профили',
            },
        ),
    ]
