# Generated by Django 6.0.1 on 2026-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_created_at_alter_lesson_lesson_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('one_time', 'Разовое'), ('recurring', 'Постоянное')], default='one_time', max_length=20, verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_date',
            field=models.DateField(blank=True, null=True, verbose_name='Изначальная дата'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Изначальное время'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Серия занятий'),
        ),
    ]
